name: Greeting on variable day

on: 
  # Triggers the workflow on push or pull request events but only for the main branch
   push:
    branches: [ main, Unit_Test]
   pull_request:
    branches: [ main ]
    
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona