name: JupyterTest

on: 
  # Triggers the workflow on push or pull request events but only for the main branch
   push:
    branches: [main]
   pull_request:
    branches: [main]
    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Cache data
      id: cache-data
      uses: actions/cache@v3
      with:
        path: .
        key: ${{ runner.os }}-data-${{ hashFiles('catalog.fits') }}
        restore-keys: |
          ${{ runner.os }}-data-
       
    - name: Install dependencies
      run: | 
        pip install jupyter nbconvert pandoc matplotlib tqdm papermill

    - name: Download data if not cached
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: |
        python UnitTest/download_data.py
   
    - name: Convert notebook to script
      run: |
        jupyter nbconvert --to script UnitTest/NotebookToTest.ipynb
    
    - name: Run Jupyter Notebook Papermill
      run: |
        papermill UnitTest/NotebookToTest.ipynb UnitTest/NotebookToTest_output.ipynb | tee notebook_output.log
    
    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace UnitTest/NotebookToTest.ipynb

